### ISSUE TITLE
Tab margin is mis-aligned and broken until clicked

### ISSUE THREAD

**Issue by MichaelScript** [Yagr/Scaff#17]
When you first load up the app there are no margins on the tab buttons. The tab buttons should be evenly spaced on the right side of the page. Upon clicking the tabs the margin is fixed. This is probably a small css fix.

**Comment by LoganxDev** [comment]
Issue was merged to master.

**Comment by MichaelScript** [comment]
It looks like this still isn't working, was there a regression?

**Comment by MichaelScript** [comment]
Good job
