### ISSUE TITLE
Double scroll bars.

### ISSUE THREAD

**Issue by MichaelScript** [Yagr/Scaff#18]
Sometimes two scroll bars one for the body and one for the content div appear. The navigation bar should remain up top of the screen and the content panel should be the only area where you can scroll. i.e: The nav bar should take up the top 5% of the screen at all time and the content should take up 95%. You should only be able to scroll in the content section not on the entire body. The scrollbar should also (if possible) remain invisible when not being scrolled.

**Comment by myamout** [comment]
I was able to remove the inner scroll bar, but the outer one for the whole page remains. I'll try and see if I can fix that as well.

**Comment by myamout** [comment]
jk we are just going to close the issue

**Comment by MichaelScript** [comment]
Well done, good job.
